<?php

namespace Database\Seeders;

use App\Models\Countries;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('countries')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');

        $countries = array(
            array('id' => 101, 'code' => 'AF', 'name' => "Afghanistan", 'phonecode' => 93,'flag' => 'flags/afghanistan.png'),
            array('id' => 2, 'code' => 'AL', 'name' => "Albania", 'phonecode' => 355,'flag' => 'flags/albania.png'),
            array('id' => 3, 'code' => 'DZ', 'name' => "Algeria", 'phonecode' => 213,'flag' => 'flags/algeria.png'),
            array('id' => 4, 'code' => 'AS', 'name' => "American Samoa", 'phonecode' => 1684,'flag' => 'flags/american_samoa.png'),
            array('id' => 5, 'code' => 'AD', 'name' => "Andorra", 'phonecode' => 376,'flag' => 'flags/andorra.png'),
            array('id' => 6, 'code' => 'AO', 'name' => "Angola", 'phonecode' => 244,'flag' => 'flags/angola.png'),
            array('id' => 7, 'code' => 'AI', 'name' => "Anguilla", 'phonecode' => 1264,'flag' => 'flags/anguilla.png'),
            array('id' => 8, 'code' => 'AQ', 'name' => "Antarctica", 'phonecode' => 672,'flag' => 'flags/antarctica.png'),
            array('id' => 9, 'code' => 'AG', 'name' => "Antigua And Barbuda", 'phonecode' => 1268,'flag' => 'flags/antigua_and_barbuda.png'),
            array('id' => 10, 'code' => 'AR', 'name' => "Argentina", 'phonecode' => 54,'flag' => 'flags/argentina.png'),
            array('id' => 11, 'code' => 'AM', 'name' => "Armenia", 'phonecode' => 374,'flag' => 'flags/armenia.png'),
            array('id' => 12, 'code' => 'AW', 'name' => "Aruba", 'phonecode' => 297,'flag' => 'flags/aruba.png'),
            array('id' => 13, 'code' => 'AU', 'name' => "Australia", 'phonecode' => 61,'flag' => 'flags/australia.png'),
            array('id' => 14, 'code' => 'AT', 'name' => "Austria", 'phonecode' => 43,'flag' => 'flags/austria.png'),
            array('id' => 15, 'code' => 'AZ', 'name' => "Azerbaijan", 'phonecode' => 994,'flag' => 'flags/azerbaijan.png'),
            array('id' => 16, 'code' => 'BS', 'name' => "Bahamas The", 'phonecode' => 1242,'flag' => 'flags/bahamas_the.png'),
            array('id' => 17, 'code' => 'BH', 'name' => "Bahrain", 'phonecode' => 973,'flag' => 'flags/bahrain.png'),
            array('id' => 18, 'code' => 'BD', 'name' => "Bangladesh", 'phonecode' => 880,'flag' => 'flags/bangladesh.png'),
            array('id' => 19, 'code' => 'BB', 'name' => "Barbados", 'phonecode' => 1246,'flag' => 'flags/barbados.png'),
            array('id' => 20, 'code' => 'BY', 'name' => "Belarus", 'phonecode' => 375,'flag' => 'flags/belarus.png'),
            array('id' => 21, 'code' => 'BE', 'name' => "Belgium", 'phonecode' => 32,'flag' => 'flags/belgium.png'),
            array('id' => 22, 'code' => 'BZ', 'name' => "Belize", 'phonecode' => 501,'flag' => 'flags/belize.png'),
            array('id' => 23, 'code' => 'BJ', 'name' => "Benin", 'phonecode' => 229,'flag' => 'flags/benin.png'),
            array('id' => 24, 'code' => 'BM', 'name' => "Bermuda", 'phonecode' => 1441,'flag' => 'flags/bermuda.png'),
            array('id' => 25, 'code' => 'BT', 'name' => "Bhutan", 'phonecode' => 975,'flag' => 'flags/bhutan.png'),
            array('id' => 26, 'code' => 'BO', 'name' => "Bolivia", 'phonecode' => 591,'flag' => 'flags/bolivia.png'),
            array('id' => 27, 'code' => 'BA', 'name' => "Bosnia and Herzegovina", 'phonecode' => 387,'flag' => 'flags/bosnia_and_herzegovina.png'),
            array('id' => 28, 'code' => 'BW', 'name' => "Botswana", 'phonecode' => 267,'flag' => 'flags/botswana.png'),


            array('id' => 29, 'code' => 'BV', 'name' => "Bouvet Island", 'phonecode' => 47,'flag' => 'flags/bouvet_island.png'),
            array('id' => 30, 'code' => 'BR', 'name' => "Brazil", 'phonecode' => 55,'flag' => 'flags/brazil.png'),
            array('id' => 31, 'code' => 'IO', 'name' => "British Indian Ocean Territory", 'phonecode' => 246,'flag' => 'flags/british_indian_ocean_territory.png'),
            array('id' => 32, 'code' => 'BN', 'name' => "Brunei", 'phonecode' => 673,'flag' => 'flags/brunei.png'),
            array('id' => 33, 'code' => 'BG', 'name' => "Bulgaria", 'phonecode' => 359,'flag' => 'flags/bulgaria.png'),
            array('id' => 34, 'code' => 'BF', 'name' => "Burkina Faso", 'phonecode' => 226,'flag' => 'flags/burkina_faso.png'),
            array('id' => 35, 'code' => 'BI', 'name' => "Burundi", 'phonecode' => 257,'flag' => 'flags/burundi.png'),
            array('id' => 36, 'code' => 'KH', 'name' => "Cambodia", 'phonecode' => 855,'flag' => 'flags/cambodia.png'),
            array('id' => 37, 'code' => 'CM', 'name' => "Cameroon", 'phonecode' => 237,'flag' => 'flags/cameroon.png'),
            array('id' => 38, 'code' => 'CA', 'name' => "Canada", 'phonecode' => 1,'flag' => 'flags/canada.png'),
            array('id' => 39, 'code' => 'CV', 'name' => "Cape Verde", 'phonecode' => 238,'flag' => 'flags/cape_verde.png'),
            array('id' => 40, 'code' => 'KY', 'name' => "Cayman Islands", 'phonecode' => 1345,'flag' => 'flags/cayman_islands.png'),
            array('id' => 41, 'code' => 'CF', 'name' => "Central African Republic", 'phonecode' => 236,'flag' => 'flags/central_african_republic.png'),
            array('id' => 42, 'code' => 'TD', 'name' => "Chad", 'phonecode' => 235,'flag' => 'flags/chad.png'),
            array('id' => 43, 'code' => 'CL', 'name' => "Chile", 'phonecode' => 56,'flag' => 'flags/chile.png'),
            array('id' => 44, 'code' => 'CN', 'name' => "China", 'phonecode' => 86,'flag' => 'flags/china.png'),
            array('id' => 45, 'code' => 'CX', 'name' => "Christmas Island", 'phonecode' => 61,'flag' => 'flags/christmas_island.png'),
            array('id' => 46, 'code' => 'CC', 'name' => "Cocos (Keeling) Islands", 'phonecode' => 672,'flag' => 'flags/cocos_(keeling)_islands.png'),
            array('id' => 47, 'code' => 'CO', 'name' => "Colombia", 'phonecode' => 57,'flag' => 'flags/colombia.png'),
            array('id' => 48, 'code' => 'KM', 'name' => "Comoros", 'phonecode' => 269,'flag' => 'flags/comoros.png'),
            array('id' => 49, 'code' => 'CG', 'name' => "Congo", 'phonecode' => 242,'flag' => 'flags/congo.png'),
            array('id' => 50, 'code' => 'CD', 'name' => "Congo The Democratic Republic Of The", 'phonecode' => 242,'flag' => 'flags/congo_the_democratic_republic_of_the.png'),
            array('id' => 51, 'code' => 'CK', 'name' => "Cook Islands", 'phonecode' => 682,'flag' => 'flags/cook_islands.png'),
            array('id' => 52, 'code' => 'CR', 'name' => "Costa Rica", 'phonecode' => 506,'flag' => 'flags/costa_rica.png'),
            array('id' => 53, 'code' => 'CI', 'name' => "Cote D Ivoire (Ivory Coast)", 'phonecode' => 225,'flag' => 'flags/cote_d_ivoire_(ivory_coast).png'),
            array('id' => 54, 'code' => 'HR', 'name' => "Croatia (Hrvatska)", 'phonecode' => 385,'flag' => 'flags/croatia_(hrvatska).png'),
            array('id' => 55, 'code' => 'CU', 'name' => "Cuba", 'phonecode' => 53,'flag' => 'flags/cuba.png'),
            array('id' => 56, 'code' => 'CY', 'name' => "Cyprus", 'phonecode' => 357,'flag' => 'flags/cyprus.png'),
            array('id' => 57, 'code' => 'CZ', 'name' => "Czech Republic", 'phonecode' => 420,'flag' => 'flags/czech_republic.png'),
            array('id' => 58, 'code' => 'DK', 'name' => "Denmark", 'phonecode' => 45,'flag' => 'flags/denmark.png'),
            array('id' => 59, 'code' => 'DJ', 'name' => "Djibouti", 'phonecode' => 253,'flag' => 'flags/djibouti.png'),
            array('id' => 60, 'code' => 'DM', 'name' => "Dominica", 'phonecode' => 1767,'flag' => 'flags/dominica.png'),
            array('id' => 61, 'code' => 'DO', 'name' => "Dominican Republic", 'phonecode' => 1809,'flag' => 'flags/dominican_republic.png'),
            // array('id' => 62, 'code' => 'TP', 'name' => "East Timor", 'phonecode' => 670,'flag' => 'flags/east_timor.png'),
            array('id' => 63, 'code' => 'EC', 'name' => "Ecuador", 'phonecode' => 593,'flag' => 'flags/ecuador.png'),
            array('id' => 64, 'code' => 'EG', 'name' => "Egypt", 'phonecode' => 20,'flag' => 'flags/egypt.png'),
            array('id' => 65, 'code' => 'SV', 'name' => "El Salvador", 'phonecode' => 503,'flag' => 'flags/el_salvador.png'),
            array('id' => 66, 'code' => 'GQ', 'name' => "Equatorial Guinea", 'phonecode' => 240,'flag' => 'flags/equatorial_guinea.png'),
            array('id' => 67, 'code' => 'ER', 'name' => "Eritrea", 'phonecode' => 291,'flag' => 'flags/eritrea.png'),
            array('id' => 68, 'code' => 'EE', 'name' => "Estonia", 'phonecode' => 372,'flag' => 'flags/estonia.png'),
            array('id' => 69, 'code' => 'ET', 'name' => "Ethiopia", 'phonecode' => 251,'flag' => 'flags/ethiopia.png'),
           // array('id' => 70, 'code' => 'XA', 'name' => "External Territories of Australia", 'phonecode' => 61,'flag' => 'flags/.png'),
            array('id' => 71, 'code' => 'FK', 'name' => "Falkland Islands", 'phonecode' => 500,'flag' => 'flags/falkland_islands.png'),
            array('id' => 72, 'code' => 'FO', 'name' => "Faroe Islands", 'phonecode' => 298,'flag' => 'flags/faroe_islands.png'),
            array('id' => 73, 'code' => 'FJ', 'name' => "Fiji Islands", 'phonecode' => 679,'flag' => 'flags/fiji_islands.png'),
            array('id' => 74, 'code' => 'FI', 'name' => "Finland", 'phonecode' => 358,'flag' => 'flags/finland.png'),
            array('id' => 75, 'code' => 'FR', 'name' => "France", 'phonecode' => 33,'flag' => 'flags/france.png'),
            array('id' => 76, 'code' => 'GF', 'name' => "French Guiana", 'phonecode' => 594,'flag' => 'flags/french_guiana.png'),
            array('id' => 77, 'code' => 'PF', 'name' => "French Polynesia", 'phonecode' => 689,'flag' => 'flags/french_polynesia.png'),
            array('id' => 78, 'code' => 'TF', 'name' => "French Southern Territories", 'phonecode' => 262,'flag' => 'flags/french_southern_territories.png'),
            array('id' => 79, 'code' => 'GA', 'name' => "Gabon", 'phonecode' => 241,'flag' => 'flags/gabon.png'),
            array('id' => 80, 'code' => 'GM', 'name' => "Gambia The", 'phonecode' => 220,'flag' => 'flags/gambia_the.png'),
            array('id' => 81, 'code' => 'GE', 'name' => "Georgia", 'phonecode' => 995,'flag' => 'flags/georgia.png'),
            array('id' => 82, 'code' => 'DE', 'name' => "Germany", 'phonecode' => 49,'flag' => 'flags/germany.png'),
            array('id' => 83, 'code' => 'GH', 'name' => "Ghana", 'phonecode' => 233,'flag' => 'flags/ghana.png'),
            array('id' => 84, 'code' => 'GI', 'name' => "Gibraltar", 'phonecode' => 350,'flag' => 'flags/gibraltar.png'),
            array('id' => 85, 'code' => 'GR', 'name' => "Greece", 'phonecode' => 30,'flag' => 'flags/greece.png'),
            array('id' => 86, 'code' => 'GL', 'name' => "Greenland", 'phonecode' => 299,'flag' => 'flags/greenland.png'),
            array('id' => 87, 'code' => 'GD', 'name' => "Grenada", 'phonecode' => 1473,'flag' => 'flags/grenada.png'),
            array('id' => 88, 'code' => 'GP', 'name' => "Guadeloupe", 'phonecode' => 590,'flag' => 'flags/guadeloupe.png'),
            array('id' => 89, 'code' => 'GU', 'name' => "Guam", 'phonecode' => 1671,'flag' => 'flags/guam.png'),
            array('id' => 90, 'code' => 'GT', 'name' => "Guatemala", 'phonecode' => 502,'flag' => 'flags/guatemala.png'),
          //  array('id' => 91, 'code' => 'XU', 'name' => "Guernsey and Alderney", 'phonecode' => 44,'flag' => 'flags/.png'),
            array('id' => 92, 'code' => 'GN', 'name' => "Guinea", 'phonecode' => 224,'flag' => 'flags/guinea.png'),
            array('id' => 93, 'code' => 'GW', 'name' => "Guinea-Bissau", 'phonecode' => 245,'flag' => 'flags/guinea-bissau.png'),
            array('id' => 94, 'code' => 'GY', 'name' => "Guyana", 'phonecode' => 592,'flag' => 'flags/guyana.png'),
            array('id' => 95, 'code' => 'HT', 'name' => "Haiti", 'phonecode' => 509,'flag' => 'flags/haiti.png'),
            array('id' => 96, 'code' => 'HM', 'name' => "Heard and McDonald Islands", 'phonecode' => 672,'flag' => 'flags/heard_and_mcdonald_islands.png'),
            array('id' => 97, 'code' => 'HN', 'name' => "Honduras", 'phonecode' => 504,'flag' => 'flags/honduras.png'),
            array('id' => 98, 'code' => 'HK', 'name' => "Hong Kong S.A.R.", 'phonecode' => 852,'flag' => 'flags/hong_kong_s.a.r..png'),
            array('id' => 99, 'code' => 'HU', 'name' => "Hungary", 'phonecode' => 36,'flag' => 'flags/hungary.png'),
            array('id' => 100, 'code' => 'IS', 'name' => "Iceland", 'phonecode' => 354,'flag' => 'flags/iceland.png'),
            array('id' => 1, 'code' => 'IN', 'name' => "India", 'phonecode' => 91,'flag' => 'flags/india.png'),
            array('id' => 102, 'code' => 'ID', 'name' => "Indonesia", 'phonecode' => 62,'flag' => 'flags/indonesia.png'),
            array('id' => 103, 'code' => 'IR', 'name' => "Iran", 'phonecode' => 98,'flag' => 'flags/iran.png'),
            array('id' => 104, 'code' => 'IQ', 'name' => "Iraq", 'phonecode' => 964,'flag' => 'flags/iraq.png'),
            array('id' => 105, 'code' => 'IE', 'name' => "Ireland", 'phonecode' => 353,'flag' => 'flags/ireland.png'),
            array('id' => 106, 'code' => 'IL', 'name' => "Israel", 'phonecode' => 972,'flag' => 'flags/israel.png'),
            array('id' => 107, 'code' => 'IT', 'name' => "Italy", 'phonecode' => 39,'flag' => 'flags/italy.png'),
            array('id' => 108, 'code' => 'JM', 'name' => "Jamaica", 'phonecode' => 1876,'flag' => 'flags/jamaica.png'),
            array('id' => 109, 'code' => 'JP', 'name' => "Japan", 'phonecode' => 81,'flag' => 'flags/japan.png'),
           // array('id' => 110, 'code' => 'XJ', 'name' => "Jersey", 'phonecode' => 44,'flag' => 'flags/.png'),
            array('id' => 111, 'code' => 'JO', 'name' => "Jordan", 'phonecode' => 962,'flag' => 'flags/jordan.png'),
            array('id' => 112, 'code' => 'KZ', 'name' => "Kazakhstan", 'phonecode' => 7,'flag' => 'flags/kazakhstan.png'),
            array('id' => 113, 'code' => 'KE', 'name' => "Kenya", 'phonecode' => 254,'flag' => 'flags/kenya.png'),
            array('id' => 114, 'code' => 'KI', 'name' => "Kiribati", 'phonecode' => 686,'flag' => 'flags/kiribati.png'),
            array('id' => 115, 'code' => 'KP', 'name' => "Korea North", 'phonecode' => 850,'flag' => 'flags/korea_north.png'),
            array('id' => 116, 'code' => 'KR', 'name' => "Korea South", 'phonecode' => 82,'flag' => 'flags/korea_south.png'),
            array('id' => 117, 'code' => 'KW', 'name' => "Kuwait", 'phonecode' => 965,'flag' => 'flags/kuwait.png'),
            array('id' => 118, 'code' => 'KG', 'name' => "Kyrgyzstan", 'phonecode' => 996,'flag' => 'flags/kyrgyzstan.png'),
            array('id' => 119, 'code' => 'LA', 'name' => "Laos", 'phonecode' => 856,'flag' => 'flags/laos.png'),
            array('id' => 120, 'code' => 'LV', 'name' => "Latvia", 'phonecode' => 371,'flag' => 'flags/latvia.png'),
            array('id' => 121, 'code' => 'LB', 'name' => "Lebanon", 'phonecode' => 961,'flag' => 'flags/lebanon.png'),
            array('id' => 122, 'code' => 'LS', 'name' => "Lesotho", 'phonecode' => 266,'flag' => 'flags/lesotho.png'),
            array('id' => 123, 'code' => 'LR', 'name' => "Liberia", 'phonecode' => 231,'flag' => 'flags/liberia.png'),
            array('id' => 124, 'code' => 'LY', 'name' => "Libya", 'phonecode' => 218,'flag' => 'flags/libya.png'),
            array('id' => 125, 'code' => 'LI', 'name' => "Liechtenstein", 'phonecode' => 423,'flag' => 'flags/liechtenstein.png'),
            array('id' => 126, 'code' => 'LT', 'name' => "Lithuania", 'phonecode' => 370,'flag' => 'flags/lithuania.png'),
            array('id' => 127, 'code' => 'LU', 'name' => "Luxembourg", 'phonecode' => 352,'flag' => 'flags/luxembourg.png'),
            array('id' => 128, 'code' => 'MO', 'name' => "Macau S.A.R.", 'phonecode' => 853,'flag' => 'flags/macau_s.a.r..png'),
            array('id' => 129, 'code' => 'MK', 'name' => "Macedonia", 'phonecode' => 389,'flag' => 'flags/macedonia.png'),
            array('id' => 130, 'code' => 'MG', 'name' => "Madagascar", 'phonecode' => 261,'flag' => 'flags/madagascar.png'),
            array('id' => 131, 'code' => 'MW', 'name' => "Malawi", 'phonecode' => 265,'flag' => 'flags/malawi.png'),
            array('id' => 132, 'code' => 'MY', 'name' => "Malaysia", 'phonecode' => 60,'flag' => 'flags/malaysia.png'),
            array('id' => 133, 'code' => 'MV', 'name' => "Maldives", 'phonecode' => 960,'flag' => 'flags/maldives.png'),
            array('id' => 134, 'code' => 'ML', 'name' => "Mali", 'phonecode' => 223,'flag' => 'flags/mali.png'),
            array('id' => 135, 'code' => 'MT', 'name' => "Malta", 'phonecode' => 356,'flag' => 'flags/malta.png'),
           // array('id' => 136, 'code' => 'XM', 'name' => "Man (Isle of)", 'phonecode' => 44,'flag' => 'flags/.png'),
            array('id' => 137, 'code' => 'MH', 'name' => "Marshall Islands", 'phonecode' => 692,'flag' => 'flags/marshall_islands.png'),
            array('id' => 138, 'code' => 'MQ', 'name' => "Martinique", 'phonecode' => 596,'flag' => 'flags/martinique.png'),
            array('id' => 139, 'code' => 'MR', 'name' => "Mauritania", 'phonecode' => 222,'flag' => 'flags/mauritania.png'),
            array('id' => 140, 'code' => 'MU', 'name' => "Mauritius", 'phonecode' => 230,'flag' => 'flags/mauritius.png'),
            array('id' => 141, 'code' => 'YT', 'name' => "Mayotte", 'phonecode' => 269,'flag' => 'flags/mayotte.png'),
            array('id' => 142, 'code' => 'MX', 'name' => "Mexico", 'phonecode' => 52,'flag' => 'flags/mexico.png'),
            array('id' => 143, 'code' => 'FM', 'name' => "Micronesia", 'phonecode' => 691,'flag' => 'flags/micronesia.png'),
            array('id' => 144, 'code' => 'MD', 'name' => "Moldova", 'phonecode' => 373,'flag' => 'flags/moldova.png'),
            array('id' => 145, 'code' => 'MC', 'name' => "Monaco", 'phonecode' => 377,'flag' => 'flags/monaco.png'),
            array('id' => 146, 'code' => 'MN', 'name' => "Mongolia", 'phonecode' => 976,'flag' => 'flags/mongolia.png'),
            array('id' => 147, 'code' => 'MS', 'name' => "Montserrat", 'phonecode' => 1664,'flag' => 'flags/montserrat.png'),
            array('id' => 148, 'code' => 'MA', 'name' => "Morocco", 'phonecode' => 212,'flag' => 'flags/morocco.png'),
            array('id' => 149, 'code' => 'MZ', 'name' => "Mozambique", 'phonecode' => 258,'flag' => 'flags/mozambique.png'),
            array('id' => 150, 'code' => 'MM', 'name' => "Myanmar", 'phonecode' => 95,'flag' => 'flags/myanmar.png'),
            array('id' => 151, 'code' => 'NA', 'name' => "Namibia", 'phonecode' => 264,'flag' => 'flags/namibia.png'),
            array('id' => 152, 'code' => 'NR', 'name' => "Nauru", 'phonecode' => 674,'flag' => 'flags/nauru.png'),
            array('id' => 153, 'code' => 'NP', 'name' => "Nepal", 'phonecode' => 977,'flag' => 'flags/nepal.png'),
           // array('id' => 154, 'code' => 'AN', 'name' => "Netherlands Antilles", 'phonecode' => 599,'flag' => 'flags/.png'),
            array('id' => 155, 'code' => 'NL', 'name' => "Netherlands The", 'phonecode' => 31,'flag' => 'flags/netherlands_the.png'),
            array('id' => 156, 'code' => 'NC', 'name' => "New Caledonia", 'phonecode' => 687,'flag' => 'flags/new_caledonia.png'),
            array('id' => 157, 'code' => 'NZ', 'name' => "New Zealand", 'phonecode' => 64,'flag' => 'flags/new_zealand.png'),
            array('id' => 158, 'code' => 'NI', 'name' => "Nicaragua", 'phonecode' => 505,'flag' => 'flags/nicaragua.png'),
            array('id' => 159, 'code' => 'NE', 'name' => "Niger", 'phonecode' => 227,'flag' => 'flags/niger.png'),
            array('id' => 160, 'code' => 'NG', 'name' => "Nigeria", 'phonecode' => 234,'flag' => 'flags/nigeria.png'),
            array('id' => 161, 'code' => 'NU', 'name' => "Niue", 'phonecode' => 683,'flag' => 'flags/niue.png'),
            array('id' => 162, 'code' => 'NF', 'name' => "Norfolk Island", 'phonecode' => 672,'flags/norfolk_island.png'),
            array('id' => 163, 'code' => 'MP', 'name' => "Northern Mariana Islands", 'phonecode' => 1670,'flag' => 'flags/northern_mariana_islands.png'),
            array('id' => 164, 'code' => 'NO', 'name' => "Norway", 'phonecode' => 47,'flag' => 'flags/norway.png'),
            array('id' => 165, 'code' => 'OM', 'name' => "Oman", 'phonecode' => 968,'flag' => 'flags/oman.png'),
            array('id' => 166, 'code' => 'PK', 'name' => "Pakistan", 'phonecode' => 92,'flag' => 'flags/pakistan.png'),
            array('id' => 167, 'code' => 'PW', 'name' => "Palau", 'phonecode' => 680,'flag' => 'flags/palau.png'),
            array('id' => 168, 'code' => 'PS', 'name' => "Palestinian Territory Occupied", 'phonecode' => 970,'flag' => 'flags/palestinian_territory_occupied.png'),
            array('id' => 169, 'code' => 'PA', 'name' => "Panama", 'phonecode' => 507,'flag' => 'flags/panama.png'),
            array('id' => 170, 'code' => 'PG', 'name' => "Papua new Guinea", 'phonecode' => 675,'flag' => 'flags/papua_new_guinea.png'),
            array('id' => 171, 'code' => 'PY', 'name' => "Paraguay", 'phonecode' => 595,'flag' => 'flags/paraguay.png'),
            array('id' => 172, 'code' => 'PE', 'name' => "Peru", 'phonecode' => 51,'flag' => 'flags/peru.png'),
            array('id' => 173, 'code' => 'PH', 'name' => "Philippines", 'phonecode' => 63,'flag' => 'flags/philippines.png'),
            array('id' => 174, 'code' => 'PN', 'name' => "Pitcairn Island", 'phonecode' => 64,'flag' => 'flags/pitcairn_island.png'),
            array('id' => 175, 'code' => 'PL', 'name' => "Poland", 'phonecode' => 48,'flag' => 'flags/poland.png'),
            array('id' => 176, 'code' => 'PT', 'name' => "Portugal", 'phonecode' => 351,'flag' => 'flags/portugal.png'),
            array('id' => 177, 'code' => 'PR', 'name' => "Puerto Rico", 'phonecode' => 1787,'flag' => 'flags/puerto_rico.png'),
            array('id' => 178, 'code' => 'QA', 'name' => "Qatar", 'phonecode' => 974,'flag' => 'flags/qatar.png'),
            array('id' => 179, 'code' => 'RE', 'name' => "Reunion", 'phonecode' => 262,'flag' => 'flags/reunion.png'),
            array('id' => 180, 'code' => 'RO', 'name' => "Romania", 'phonecode' => 40,'flag' => 'flags/romania.png'),
            array('id' => 181, 'code' => 'RU', 'name' => "Russia", 'phonecode' => 70,'flag' => 'flags/russia.png'),
            array('id' => 182, 'code' => 'RW', 'name' => "Rwanda", 'phonecode' => 250,'flag' => 'flags/rwanda.png'),
            array('id' => 183, 'code' => 'SH', 'name' => "Saint Helena", 'phonecode' => 290,'flag' => 'flags/saint_helena.png'),
            array('id' => 184, 'code' => 'KN', 'name' => "Saint Kitts And Nevis", 'phonecode' => 1869,'flag' => 'flags/saint_kitts_and_nevis.png'),
            array('id' => 185, 'code' => 'LC', 'name' => "Saint Lucia", 'phonecode' => 1758,'flag' => 'flags/saint_lucia.png'),
            array('id' => 186, 'code' => 'PM', 'name' => "Saint Pierre and Miquelon", 'phonecode' => 508,'flag' => 'flags/saint_pierre_and_miquelon.png'),
            array('id' => 187, 'code' => 'VC', 'name' => "Saint Vincent And The Grenadines", 'phonecode' => 1784,'flag' => 'flags/saint_vincent_and_the_grenadines.png'),
            array('id' => 188, 'code' => 'WS', 'name' => "Samoa", 'phonecode' => 684,'flag' => 'flags/samoa.png'),
            array('id' => 189, 'code' => 'SM', 'name' => "San Marino", 'phonecode' => 378,'flag' => 'flags/san_marino.png'),
            array('id' => 190, 'code' => 'ST', 'name' => "Sao Tome and Principe", 'phonecode' => 239,'flag' => 'flags/sao_tome_and_principe.png'),
            array('id' => 191, 'code' => 'SA', 'name' => "Saudi Arabia", 'phonecode' => 966,'flag' => 'flags/saudi_arabia.png'),
            array('id' => 192, 'code' => 'SN', 'name' => "Senegal", 'phonecode' => 221,'flag' => 'flags/senegal.png'),
            array('id' => 193, 'code' => 'RS', 'name' => "Serbia", 'phonecode' => 381,'flag' => 'flags/serbia.png'),
            array('id' => 194, 'code' => 'SC', 'name' => "Seychelles", 'phonecode' => 248,'flag' => 'flags/seychelles.png'),
            array('id' => 195, 'code' => 'SL', 'name' => "Sierra Leone", 'phonecode' => 232,'flag' => 'flags/sierra_leone.png'),
            array('id' => 196, 'code' => 'SG', 'name' => "Singapore", 'phonecode' => 65,'flag' => 'flags/singapore.png'),
            array('id' => 197, 'code' => 'SK', 'name' => "Slovakia", 'phonecode' => 421,'flag' => 'flags/slovakia.png'),
            array('id' => 198, 'code' => 'SI', 'name' => "Slovenia", 'phonecode' => 386,'flag' => 'flags/slovenia.png'),
          //  array('id' => 199, 'code' => 'XG', 'name' => "Smaller Territories of the UK", 'phonecode' => 44,'flag' => 'flags/.png'),
            array('id' => 200, 'code' => 'SB', 'name' => "Solomon Islands", 'phonecode' => 677,'flag' => 'flags/solomon_islands.png'),
            array('id' => 201, 'code' => 'SO', 'name' => "Somalia", 'phonecode' => 252,'flag' => 'flags/somalia.png'),
            array('id' => 202, 'code' => 'ZA', 'name' => "South Africa", 'phonecode' => 27,'flag' => 'flags/south_africa.png'),
            array('id' => 203, 'code' => 'GS', 'name' => "South Georgia", 'phonecode' => 500,'flag' => 'flags/south_georgia.png'),
            array('id' => 204, 'code' => 'SS', 'name' => "South Sudan", 'phonecode' => 211,'flag' => 'flags/south_sudan.png'),
            array('id' => 205, 'code' => 'ES', 'name' => "Spain", 'phonecode' => 34,'flag' => 'flags/spain.png'),
            array('id' => 206, 'code' => 'LK', 'name' => "Sri Lanka", 'phonecode' => 94,'flag' => 'flags/sri_lanka.png'),
            array('id' => 207, 'code' => 'SD', 'name' => "Sudan", 'phonecode' => 249,'flag' => 'flags/sudan.png'),
            array('id' => 208, 'code' => 'SR', 'name' => "Suriname", 'phonecode' => 597,'flag' => 'flags/suriname.png'),
            array('id' => 209, 'code' => 'SJ', 'name' => "Svalbard And Jan Mayen Islands", 'phonecode' => 47,'flag' => 'flags/svalbard_and_jan_mayen_islands.png'),
            array('id' => 210, 'code' => 'SZ', 'name' => "Swaziland", 'phonecode' => 268,'flag' => 'flags/swaziland.png'),
            array('id' => 211, 'code' => 'SE', 'name' => "Sweden", 'phonecode' => 46,'flag' => 'flags/sweden.png'),
            array('id' => 212, 'code' => 'CH', 'name' => "Switzerland", 'phonecode' => 41,'flag' => 'flags/switzerland.png'),
            array('id' => 213, 'code' => 'SY', 'name' => "Syria", 'phonecode' => 963,'flag' => 'flags/syria.png'),
            array('id' => 214, 'code' => 'TW', 'name' => "Taiwan", 'phonecode' => 886,'flag' => 'flags/taiwan.png'),
            array('id' => 215, 'code' => 'TJ', 'name' => "Tajikistan", 'phonecode' => 992,'flag' => 'flags/tajikistan.png'),
            array('id' => 216, 'code' => 'TZ', 'name' => "Tanzania", 'phonecode' => 255,'flag' => 'flags/tanzania.png'),
            array('id' => 217, 'code' => 'TH', 'name' => "Thailand", 'phonecode' => 66,'flag' => 'flags/thailand.png'),
            array('id' => 218, 'code' => 'TG', 'name' => "Togo", 'phonecode' => 228,'flag' => 'flags/togo.png'),
            array('id' => 219, 'code' => 'TK', 'name' => "Tokelau", 'phonecode' => 690,'flag' => 'flags/tokelau.png'),
            array('id' => 220, 'code' => 'TO', 'name' => "Tonga", 'phonecode' => 676,'flag' => 'flags/tonga.png'),
            array('id' => 221, 'code' => 'TT', 'name' => "Trinidad And Tobago", 'phonecode' => 1868,'flag' => 'flags/trinidad_and_tobago.png'),
            array('id' => 222, 'code' => 'TN', 'name' => "Tunisia", 'phonecode' => 216,'flag' => 'flags/tunisia.png'),
            array('id' => 223, 'code' => 'TR', 'name' => "Turkey", 'phonecode' => 90,'flag' => 'flags/turkey.png'),
            array('id' => 224, 'code' => 'TM', 'name' => "Turkmenistan", 'phonecode' => 7370,'flag' => 'flags/turkmenistan.png'),
            array('id' => 225, 'code' => 'TC', 'name' => "Turks And Caicos Islands", 'phonecode' => 1649,'flag' => 'flags/turks_and_caicos_islands.png'),
            array('id' => 226, 'code' => 'TV', 'name' => "Tuvalu", 'phonecode' => 688,'flag' => 'flags/tuvalu.png'),
            array('id' => 227, 'code' => 'UG', 'name' => "Uganda", 'phonecode' => 256,'flag' => 'flags/uganda.png'),
            array('id' => 228, 'code' => 'UA', 'name' => "Ukraine", 'phonecode' => 380,'flag' => 'flags/ukraine.png'),
            array('id' => 229, 'code' => 'AE', 'name' => "United Arab Emirates", 'phonecode' => 971,'flag' => 'flags/united_arab_emirates.png'),
            array('id' => 230, 'code' => 'GB', 'name' => "United Kingdom", 'phonecode' => 44,'flag' => 'flags/united_kingdom.png'),
            array('id' => 231, 'code' => 'US', 'name' => "United States", 'phonecode' => 1,'flag' => 'flags/united_states.png'),

            array('id' => 232, 'code' => 'UM', 'name' => "United States Minor Outlying Islands", 'phonecode' => 1,'flag' => 'flags/united_states_minor_outlying_islands.png'),
            array('id' => 233, 'code' => 'UY', 'name' => "Uruguay", 'phonecode' => 598,'flag' => 'flags/uruguay.png'),
            array('id' => 234, 'code' => 'UZ', 'name' => "Uzbekistan", 'phonecode' => 998,'flag' => 'flags/uzbekistan.png'),
            array('id' => 235, 'code' => 'VU', 'name' => "Vanuatu", 'phonecode' => 678,'flag' => 'flags/vanuatu.png'),
            array('id' => 236, 'code' => 'VA', 'name' => "Vatican City State (Holy See)", 'phonecode' => 39,'flag' => 'flags/vatican_city_state_(holy_see).png'),
            array('id' => 237, 'code' => 'VE', 'name' => "Venezuela", 'phonecode' => 58,'flag' => 'flags/venezuela.png'),
            array('id' => 238, 'code' => 'VN', 'name' => "Vietnam", 'phonecode' => 84,'flag' => 'flags/vietnam.png'),
            array('id' => 239, 'code' => 'VG', 'name' => "Virgin Islands (British)", 'phonecode' => 1284,'flag' => 'flags/virgin_islands_(british).png'),
            array('id' => 240, 'code' => 'VI', 'name' => "Virgin Islands (US)", 'phonecode' => 1340,'flag' => 'flags/virgin_islands_(us).png'),
            array('id' => 241, 'code' => 'WF', 'name' => "Wallis And Futuna Islands", 'phonecode' => 681,'flag' => 'flags/wallis_and_futuna_islands.png'),
            array('id' => 242, 'code' => 'EH', 'name' => "Western Sahara", 'phonecode' => 212,'flag' => 'flags/western_sahara.png'),
            array('id' => 243, 'code' => 'YE', 'name' => "Yemen", 'phonecode' => 967,'flag' => 'flags/yemen.png'),
            // array('id' => 244, 'code' => 'YU', 'name' => "Yugoslavia", 'phonecode' => 38,'flag' => 'flags/yugoslavia.png'),
            array('id' => 245, 'code' => 'ZM', 'name' => "Zambia", 'phonecode' => 260,'flag' => 'flags/zambia.png'),
            array('id' => 246, 'code' => 'ZW', 'name' => "Zimbabwe", 'phonecode' => 263,'flag' => 'flags/zimbabwe.png'),
        );
        foreach ($countries as $key => $val) {
            $imageName = str_replace(' ', '_', strtolower(trim($val['name'])));
            $item= [
                'id' => $val['id'],
                'code' =>  $val['code'],
                'name' => $val['name'],
                'phonecode' => $val['phonecode'],
                'flag' => 'flags/'.$imageName.'.png',
            ];
            $countries =  Countries::updateOrCreate(['id' => $val['id']], $item);
        }
       // DB::table('countries')->insert($countries);
    }
}
